<?xml version="1.0"?>
<robot name="elevator" 
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="deg2rad" value="0.01745329251"/>
  <xacro:property name="length" value="1.0" /> <!-- length is the height of pole when retracted -->
  <xacro:property name="spread" value="0.9" /> <!-- spread is how much the pole moves -->
  <xacro:property name="outer_radius" value="0.07" />
  <xacro:property name="inner_radius" value="0.05" />

  <xacro:macro name="elevator" params="prefix:='' parent *origin">
    <xacro:macro name="solid_cuboid_inertia" params="m h d w">
      <inertia ixx="${(m*(h*h+d*d))/12}" ixy = "0" ixz = "0" iyy="${(m*(w*w+d*d))/12}" iyz = "0" izz="${(m*(w*w+h*h))/12}" />
    </xacro:macro>
  
    <!--fixed joint -->
    <joint name="${prefix}elevator_base_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${prefix}elevator_base_link"/>
      <xacro:insert_block name="origin" />
    </joint>
  
    <link name="${prefix}elevator_base_link">
      <visual>
        <origin xyz="0 0 ${length/2.0}" rpy="0 0 0" />
        <geometry>
            <cylinder radius="${outer_radius}" length="${length}"/>
        </geometry>
      </visual>
  
      <!--inertial>
        <mass value="1" />
        <origin xyz="0 0 0" />
        <solid_cuboid_inertia m="1" h="0.1" d="0.1" w="0.1"/>
      </inertial-->
      <inertial>
        <mass value="0.001"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
    </link>
  
    <!-- Elevator structure -->
    <joint name="${prefix}elevator_joint" type="prismatic">
      <parent link="${prefix}elevator_base_link"/>
      <origin xyz="0.0 0.0 ${length}" rpy="0 0 0" />
      <child link="${prefix}elevator_link"/>
      <axis xyz="0 0 1"/>
      <limit lower="0.0" upper="${spread}" effort="100.0" velocity="0.07"/>
      <!--<xacro:insert_block name="origin" />-->
    </joint>
  
    <link name="${prefix}elevator_link">
      <visual>
        <origin xyz="0 0 -${length/2.0}" rpy="0 0 0" />
        <geometry>
            <cylinder radius="${inner_radius}" length="${length}"/>
        </geometry>
      </visual>
      <!--inertial>
        <mass value="0.1" />
        <origin xyz="0 0 -0.27" />
        <solid_cuboid_inertia m="0.1" h="0.1" d="0.1" w="0.1"/>
      </inertial-->
      <inertial>
        <mass value="0.001"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
    </link>
    <transmission name="${prefix}elevator_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}elevator_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}elevator_motor">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </actuator>
    </transmission>
  </xacro:macro>
</robot>
