local_costmap:
  global_frame: $(arg odom_frame)
  robot_base_frame: $(arg base_frame)
  update_frequency: 10.0
  static_map: false
  rolling_window: true
  width: 30.0 #5
  height: 30.0 #5
  resolution: 0.05 #0.05

  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0

  plugins:
    - name: obstacle_layer
      type: "costmap_2d::VoxelLayer"

  obstacle_layer:
    enabled: true
